export type Point = { lat: number; lng: number; name: string };
export type Trail = { id: string; name: string; region: string; distance: number; difficulty: 'Easy' | 'Moderate' | 'Challenging'; terrain: string; description: string; point: Point; image: string; source: string; note: string };
const central = 'https://www.nparks.gov.sg/visit/parks/central-catchment-nature-reserve/activities';
export const trails: Trail[] = [
  { id: 'eastern', name: 'Eastern Corridor', region: 'East', distance: 18, difficulty: 'Challenging', terrain: 'Park connectors · Waterfront', description: 'Link Pasir Ris and East Coast through neighbourhood green spaces and Bedok Reservoir.', point: { lat: 1.3815, lng: 103.955, name: 'Pasir Ris Park' }, image: 'photo-1472396961693-142e6e269027', source: 'https://www.nparks.gov.sg/visit/parks', note: 'NParks lists an 18 km corridor. Our challenging rating reflects its length. Choose a shorter section if needed; connectors include urban stretches.' },
  { id: 'northern', name: 'Northern Explorer Loop', region: 'North', distance: 25, difficulty: 'Challenging', terrain: 'Park connectors · Neighbourhoods', description: 'Discover the northern side of the island through parks in Woodlands, Sembawang and Yishun.', point: { lat: 1.4457, lng: 103.7805, name: 'Woodlands Waterfront Park' }, image: 'photo-1473448912268-2022ce9509d8', source: 'https://www.nparks.gov.sg/visit/parks', note: 'NParks lists a 25 km network linking 11 parks and nature areas. Our challenging rating reflects the full length. Plan shorter segments and transport home.' },
  { id: 'treetop', name: 'MacRitchie TreeTop Walk', region: 'Central', distance: 10.3, difficulty: 'Challenging', terrain: 'Forest · Suspension bridge', description: 'Go a little deeper. Rainforest paths lead to a different perspective above the canopy.', point: { lat: 1.3415, lng: 103.833, name: 'MacRitchie Reservoir Park' }, image: 'photo-1448375240586-882707db888b', source: central, note: 'NParks Route 3: 10.3 km loop. TreeTop Walk closes Mondays except public holidays; check current opening hours and last entry.' },
  { id: 'prunus', name: 'Prunus & Petai Trail', region: 'Central', distance: 3, difficulty: 'Easy', terrain: 'Reservoir · Boardwalk', description: 'Slow down by the water on a gentle boardwalk through the reservoir’s green edges.', point: { lat: 1.3427, lng: 103.8351, name: 'Prunus Trail entrance' }, image: 'photo-1472396961693-142e6e269027', source: central, note: 'NParks Route 1: 3 km. Check boardwalk access before setting out.' },
  { id: 'ridges', name: 'The Southern Ridges', region: 'South', distance: 10, difficulty: 'Moderate', terrain: 'Ridges · City views', description: 'A green escape above the city, linking hilltop parks, walkways and sweeping views.', point: { lat: 1.2737, lng: 103.8177, name: 'Mount Faber Park' }, image: 'photo-1441974231531-c6227db76b6e', source: 'https://www.nparks.gov.sg/docs/default-source/parks-docs/shared/hortpark-southern-ridges-diy-walk.pdf', note: '10 km trail network, not a single verified itinerary. Choose your endpoints and check walkway closures with NParks.' },
  { id: 'rail', name: 'Rail Corridor Central', region: 'West', distance: 4, difficulty: 'Easy', terrain: 'Heritage · Green corridor', description: 'Follow the old railway through a quieter side of Singapore, from heritage bridges to leafy paths.', point: { lat: 1.3343, lng: 103.7814, name: 'Bukit Timah Railway Station' }, image: 'photo-1473448912268-2022ce9509d8', source: 'https://railcorridor.nparks.gov.sg/visit-rail-corridor/', note: 'Approximately 4 km central section to Hillview. Main trail is unlit; plan for daylight.' },
  { id: 'timah', name: 'Bukit Timah Summit Trail', region: 'West', distance: 1.2, difficulty: 'Challenging', terrain: 'Steep climb · Rainforest', description: 'A short but rewarding climb into one of Singapore’s most treasured forest reserves.', point: { lat: 1.3474, lng: 103.776, name: 'Bukit Timah Visitor Centre' }, image: 'photo-1511497584788-876760111969', source: 'https://www.nparks.gov.sg/docs/default-source/parks-docs/bukit-timah-nature-reserve/bukit-timah-nature-reserve-trail-guide.pdf', note: 'Published route length is 1.2 km one way. Allow for the return journey; steep slopes and steps increase effort.' },
  { id: 'windsor', name: 'Windsor to TreeTop Walk', region: 'Central', distance: 7, difficulty: 'Challenging', terrain: 'Forest · Canopy views', description: 'Trade city noise for birdsong on an adventurous loop from Windsor Nature Park.', point: { lat: 1.3595, lng: 103.826, name: 'Windsor Nature Park entrance' }, image: 'photo-1448375240586-882707db888b', source: central, note: 'NParks Route 6: 7 km loop. TreeTop Walk opening hours and one-way access apply.' },
];
export const places: Point[] = [...trails.map(t => t.point), { lat: 1.3544, lng: 103.7861, name: 'Singapore Quarry' }, { lat: 1.2777, lng: 103.8052, name: 'Henderson Waves' }, { lat: 1.2795, lng: 103.8009, name: 'HortPark' }, { lat: 1.4044, lng: 103.9198, name: 'Coney Island west entrance' }, { lat: 1.4466, lng: 103.7295, name: 'Sungei Buloh visitor centre' }, { lat: 1.3009, lng: 103.9122, name: 'East Coast Park, Marine Cove' }];
export type Fitness = 'Relaxed' | 'Regular' | 'Experienced';
export const speeds: Record<Fitness, number> = { Relaxed: 2.5, Regular: 3.5, Experienced: 4.5 };
export function minutes(distance: number, fitness: Fitness, difficulty = 'Easy') { return Math.ceil(distance / speeds[fitness] * 60 * (difficulty === 'Challenging' ? 1.35 : difficulty === 'Moderate' ? 1.15 : 1) * 1.15); }
export function duration(value: number) { return value < 60 ? `${value} min` : `${Math.floor(value / 60)}h ${value % 60}m`; }
export function directDistance(points: Point[]) { return points.slice(1).reduce((total, p, i) => { const a = points[i]; const r = Math.PI / 180; const h = Math.sin((p.lat-a.lat)*r/2)**2 + Math.cos(a.lat*r)*Math.cos(p.lat*r)*Math.sin((p.lng-a.lng)*r/2)**2; return total + 6371*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h)); }, 0); }
export function validPoint(p: unknown): p is Point { if (!p || typeof p !== 'object') return false; const v = p as Point; return Number.isFinite(v.lat) && Number.isFinite(v.lng) && v.lat >= 1.16 && v.lat <= 1.48 && v.lng >= 103.6 && v.lng <= 104.1 && typeof v.name === 'string' && v.name.length <= 160; }
