'use client';

import dynamic from 'next/dynamic';
import { useEffect, useMemo, useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUp, Bookmark, Check, ChevronDown, Clock3, Compass, Download, Footprints, Heart, Leaf, Map as MapIcon, MapPin, Mountain, Plus, Route, Search, ShieldCheck, SlidersHorizontal, Sun, Trees, X } from 'lucide-react';
import { directDistance, duration, minutes, places, trails, validPoint, type Fitness, type Point } from '@/lib/trails';

const TrailMap = dynamic(() => import('@/components/trail-map'), { ssr: false, loading: () => <div className="map-loading"><MapIcon/> Finding your next escape…</div> });
import { useWalkingRoute } from '@/hooks/use-walking-route';
const emptyPoints: Point[] = [];

export default function Home() {
  const [tab,setTab] = useState<'explore'|'plan'|'saved'>('explore');
  const [query,setQuery] = useState(''); const [difficulty,setDifficulty] = useState('All levels'); const [region,setRegion] = useState('All Singapore');
  const [maxDistance,setMaxDistance] = useState(30); const [filters,setFilters] = useState(false); const [fitness,setFitness] = useState<Fitness>('Regular');
  const [saved,setSaved] = useState<string[]>([]); const [ready,setReady] = useState(false); const [selected,setSelected] = useState<string|null>(null);
  const [points,setPoints] = useState<Point[]>([]); const { result, routeError, loading, retry } = useWalkingRoute(points);
  const [toast,setToast] = useState(''); const [guide,setGuide] = useState(false); const [budget,setBudget] = useState(4); const [place,setPlace] = useState('');
  useEffect(() => {
    if (!guide) return;
    const previous = document.activeElement as HTMLElement | null;
    const overflow = document.body.style.overflow; document.body.style.overflow = 'hidden';
    function keyboard(event: KeyboardEvent) {
      if (event.key === 'Escape') setGuide(false);
      if (event.key !== 'Tab') return;
      const controls = document.querySelectorAll<HTMLElement>('.guide-modal button, .guide-modal input, .guide-modal a');
      const first = controls[0], last = controls[controls.length-1];
      if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); }
      else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); }
    }
    document.addEventListener('keydown',keyboard);
    return () => { document.body.style.overflow = overflow; document.removeEventListener('keydown',keyboard); previous?.focus(); };
  }, [guide]);
  useEffect(() => { try { const favourites: unknown = JSON.parse(localStorage.getItem('trailfolk-saved') || '[]'); if (Array.isArray(favourites)) setSaved(favourites.filter((id): id is string => typeof id === 'string' && trails.some(t => t.id === id))); const draft: unknown = JSON.parse(localStorage.getItem('trailfolk-plan') || '[]'); if (Array.isArray(draft) && draft.length <= 8 && draft.every(validPoint)) setPoints(draft); } catch {} setReady(true); }, []);
  useEffect(() => { if (ready) try { localStorage.setItem('trailfolk-saved',JSON.stringify(saved)); localStorage.setItem('trailfolk-plan',JSON.stringify(points)); } catch {} }, [saved,points,ready]);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''),3500); return () => clearTimeout(timer); }, [toast]);
  const visible = useMemo(() => trails.filter(t => (!query || `${t.name} ${t.region} ${t.terrain}`.toLowerCase().includes(query.toLowerCase())) && (difficulty === 'All levels' || t.difficulty === difficulty) && (region === 'All Singapore' || t.region === region) && t.distance <= maxDistance && (tab !== 'saved' || saved.includes(t.id))).sort((a,b) => fitness === 'Relaxed' ? Number(a.difficulty !== 'Easy') - Number(b.difficulty !== 'Easy') : Number(a.distance > 15) - Number(b.distance > 15)),[query,difficulty,region,maxDistance,tab,saved,fitness]);
  const activeTrail = trails.find(t => t.id === selected);
  function addPoint(p: Point) { if (!validPoint(p)) return setToast('Please choose a location within Singapore.'); if (points.length >= 8) return setToast('Your route can have up to 8 stops.'); setPoints(previous => previous.length < 8 ? [...previous,p] : previous); }
  function toggleSave(id: string) { setSaved(previous => previous.includes(id) ? previous.filter(v => v !== id) : [...previous,id]); }
  function reorder(index: number, delta: number) { setPoints(previous => { const updated = [...previous]; [updated[index],updated[index+delta]] = [updated[index+delta],updated[index]]; return updated; }); }
  function exportPlan() { const content = { name:'My Trailfolk Singapore hike', stops:points, routing: result ? 'OneMap walking route; access and closures not verified' : 'UNVERIFIED: no walking route available', distanceKm:result?.distance ?? null, straightLineLowerBoundKm:directDistance(points), fitness, estimatedMinutes: result ? minutes(result.distance,fitness) : null, geometry: result?.geometry ?? [], legs: result?.legs ?? [], warnings: result?.warnings ?? [], calculatedAt: result?.calculatedAt ?? null, note:'Time includes 15% rest allowance. Elevation, weather and closures are not included. Check NParks before leaving.' }; const url = URL.createObjectURL(new Blob([JSON.stringify(content,null,2)],{type:'application/json'})); const a = document.createElement('a'); a.href=url; a.download='trailfolk-hike.json'; a.click(); URL.revokeObjectURL(url); setToast('Your itinerary has been downloaded.'); }
  const estimate = result ? minutes(result.distance,fitness) : null;
  return <>
    <header className="header"><a href="/" className="brand" aria-label="Trailfolk home"><span className="brand-icon"><Mountain size={24}/></span>trailfolk<span className="brand-sg">SG</span></a><nav aria-label="Main navigation"><button className={tab==='explore'?'nav-active':''} onClick={() => setTab('explore')}>Explore trails</button><button className={tab==='plan'?'nav-active':''} onClick={() => setTab('plan')}>Route planner</button><button onClick={() => setGuide(true)}>Hiking essentials <span className="nav-dot"/></button></nav><button className={`saved-button ${tab==='saved'?'selected':''}`} onClick={() => setTab('saved')}><Bookmark size={17}/> Saved trails <span>{saved.length}</span></button></header>
    <main>
      <section className="hero"><div className="hero-content"><div className="eyebrow"><span/> LESS CITY. MORE POSSIBILITY.</div><h1>Your next adventure.<br/><span>Closer than you think.</span></h1><p>Find your kind of trail. Make it your own.<br/>Discover Singapore, one green escape at a time.</p><button className="primary hero-button" onClick={() => {setTab('plan'); document.getElementById('explore')?.scrollIntoView({behavior:'smooth'});}}>Plan your adventure <ArrowRight size={17}/></button><div className="hero-footer"><span><MapPin size={14}/> Made for Singapore</span><i/> A little outdoors goes a long way.</div></div><div className="hero-image" role="img" aria-label="Sunlight filtering through a lush green forest"><div className="photo-shade"/><div className="image-caption"><span className="caption-label"><Trees size={16}/> THE OUTDOORS IS CALLING</span><h2>Take the scenic route.</h2><p>There’s more green than you think.</p></div><span className="photo-note">A little inspiration from nature</span></div></section>
      <section className="benefits" aria-label="Planner benefits"><div><span className="benefit-icon"><Compass/></span><p><strong>Find your trail</strong><small>Little escapes. Big discoveries.</small></p></div><div><span className="benefit-icon"><Route/></span><p><strong>Your route, your way</strong><small>Connect the places you love.</small></p></div><div><span className="benefit-icon"><Footprints/></span><p><strong>Go at your own pace</strong><small>Plans that fit your fitness.</small></p></div><a href="https://www.nparks.gov.sg/visit" target="_blank" rel="noreferrer"><ShieldCheck size={21}/><span>Explore thoughtfully<br/><strong>Check park advisories ↗</strong></span></a></section>
      <section id="explore" className="explore-section"><div className="section-heading"><div><div className="eyebrow dark">A BREATH OF FRESH AIR</div><h2>{tab === 'plan' ? 'Make the journey yours.' : tab === 'saved' ? 'A little inspiration, saved.' : 'Find your next green escape.'}</h2><p>{tab === 'plan' ? 'Pick your stops. Set your pace. See where the day takes you.' : 'From easy waterside wanders to a climb worth the effort.'}</p></div><div className="view-switch"><button className={tab!=='plan'?'active':''} onClick={() => setTab('explore')}><Trees size={16}/> Discover</button><button className={tab==='plan'?'active':''} onClick={() => setTab('plan')}><Route size={16}/> Build a route</button></div></div>
      <div className="toolbar"><label className="search"><Search size={19}/><input aria-label="Search trails" placeholder="Search trails, parks, a little adventure…" value={query} onChange={e=>setQuery(e.target.value)}/>{query && <button aria-label="Clear search" onClick={()=>setQuery('')}><X size={16}/></button>}</label><label className="select-control"><MapPin size={16}/><select aria-label="Region" value={region} onChange={e=>setRegion(e.target.value)}>{['All Singapore','Central','West','South','East','North'].map(x=><option key={x}>{x}</option>)}</select><ChevronDown size={14}/></label><label className="select-control"><Mountain size={17}/><select aria-label="Trail difficulty" value={difficulty} onChange={e=>setDifficulty(e.target.value)}>{['All levels','Easy','Moderate','Challenging'].map(x=><option key={x}>{x}</option>)}</select><ChevronDown size={14}/></label><button className={`filter-button ${filters?'selected':''}`} onClick={()=>setFilters(!filters)} aria-expanded={filters}><SlidersHorizontal size={17}/> Filters{maxDistance<30 && <span className="nav-dot"/>}</button></div>
      {filters && <div className="filter-panel"><label>Maximum published trail length <strong>{maxDistance} km</strong><input type="range" min="1" max="30" value={maxDistance} onChange={e=>setMaxDistance(Number(e.target.value))}/></label><label>My walking style<select value={fitness} onChange={e=>setFitness(e.target.value as Fitness)}>{['Relaxed','Regular','Experienced'].map(x=><option key={x}>{x}</option>)}</select></label><button className="text-button" onClick={()=>{setMaxDistance(30);setRegion('All Singapore');setDifficulty('All levels');setQuery('');}}>Reset filters</button></div>}
      <div className={`workspace ${tab==='plan'?'planning':''}`}><div className="list-panel">
      {tab === 'plan' ? <div className="planner"><div className="list-heading"><strong>Your adventure plan</strong><span>{points.length}/8 stops</span></div><p className="muted">Add a place or tap the map. Drag numbered stops to adjust your route; distance recalculates automatically.</p><div className="place-add"><select aria-label="Choose a stop" value={place} onChange={e=>setPlace(e.target.value)}><option value="">Choose a place…</option>{places.map((p,i)=><option value={i} key={p.name}>{p.name}</option>)}</select><button className="primary" aria-label="Add selected stop" disabled={place===''} onClick={()=>{addPoint(places[Number(place)]);setPlace('');}}><Plus size={19}/></button></div>
      {points.length === 0 && <div className="empty-plan"><Route size={32}/><h3>Every adventure starts somewhere.</h3><p>Choose your first stop to get going.</p></div>}
      <ol className="stop-list">{points.map((p,i)=><li key={`${i}-${p.lat}-${p.lng}`}><span className="stop-number">{i+1}</span><span>{p.name}</span><div><button aria-label={`Move stop ${i+1} earlier`} disabled={i===0} onClick={()=>reorder(i,-1)}><ArrowUp size={14}/></button><button aria-label={`Move stop ${i+1} later`} disabled={i===points.length-1} onClick={()=>reorder(i,1)}><ArrowDown size={14}/></button><button aria-label={`Remove stop ${i+1}`} onClick={()=>setPoints(points.filter((_,j)=>j!==i))}><X size={15}/></button></div></li>)}</ol>
      <div className="pace-box"><h3><Footprints size={17}/> Make room for your pace</h3><div className="pace-options">{(['Relaxed','Regular','Experienced'] as Fitness[]).map(x=><button key={x} className={fitness===x?'active':''} onClick={()=>setFitness(x)}>{x}</button>)}</div><label className="time-budget">Time available <strong>{budget} hours</strong><input type="range" min="1" max="10" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></label></div>
      {points.length>1 && <div className="route-summary" aria-live="polite"><div className="route-status">{loading?'Finding a walking route…':result?'OneMap walking route':'Route not verified'}</div><div className="route-stats"><div><strong>{result ? result.distance.toFixed(3) : '—'}<small> km</small></strong><span>{result?'OneMap walking distance':'Waiting for walking distance'}</span></div><div><strong>{estimate?duration(estimate):'—'}</strong><span>Estimated time with breaks</span></div></div>{routeError && <div className="route-warning"><p>{routeError}</p><button className="text-button" onClick={retry}>Retry directions</button></div>}{result && <><ol className="route-legs">{result.legs.map((leg,i)=><li key={i}><span>Stop {i+1} → {i+2}</span><strong>{leg.distance.toFixed(3)} km</strong></li>)}</ol>{result.warnings.map(warning=><p className="route-warning" key={warning}>{warning}</p>)}<p className="small-note">Recalculated {new Date(result.calculatedAt).toLocaleTimeString("en-SG",{hour:"2-digit",minute:"2-digit",timeZone:"Asia/Singapore"})} SGT · Paths supplied by OneMap. Check current access and closures.</p></>}{estimate && <><p className={estimate>budget*60?'route-warning':'fit-message'}>{estimate>budget*60?'This may exceed your time budget. Remove a stop or allow more time.':'Within your time budget at this pace.'}</p><p className="muted">Time uses your walking pace plus 15% for breaks. Hills, heat, closures and trail conditions are not included; this is an effort estimate, not a safety assessment.</p></>}</div>}
      <div className="plan-buttons"><button className="primary" disabled={!result || loading} onClick={exportPlan}><Download size={16}/> Export itinerary</button><button className="text-button" disabled={!points.length} onClick={()=>setPoints([])}>Clear route</button></div><p className="small-note">Draft saved on this device when browser storage is available. You can reorder or remove stops above.</p></div> : <><div className="list-heading"><span><strong>{visible.length} trails</strong> to get you outside</span><span className="curated"><Leaf size={13}/> Curated escapes</span></div><div className="trail-list">{visible.map(t=><article className={`trail-card ${selected===t.id?'active':''}`} key={t.id}><button className="trail-photo" style={{backgroundImage:`url(https://images.unsplash.com/${t.image}?auto=format&fit=crop&w=500&q=80)`}} onClick={()=>setSelected(t.id)} aria-label={`View ${t.name} on map`}><span className={`difficulty ${t.difficulty.toLowerCase()}`}>{t.difficulty}</span><span className="illustrative">Nature inspiration</span></button><div className="trail-info"><div className="trail-location"><MapPin size={12}/>{t.region} Singapore<button aria-label={`${saved.includes(t.id)?'Unsave':'Save'} ${t.name}`} aria-pressed={saved.includes(t.id)} onClick={()=>toggleSave(t.id)}><Heart size={18} fill={saved.includes(t.id)?'currentColor':'none'}/></button></div><button className="trail-title" onClick={()=>setSelected(t.id)}>{t.name}</button><p>{t.terrain}</p><div className="trail-stats"><span><Route size={13}/>{t.distance} km</span><span><Clock3 size={13}/>{duration(minutes(t.distance,fitness,t.difficulty))} est.</span></div><div className="card-bottom"><span>{t.difficulty==='Easy'?'A gentler adventure':t.difficulty==='Challenging'?'For a little challenge':'A rewarding wander'}</span><button aria-label={`Details for ${t.name}`} onClick={()=>setSelected(t.id)}><ArrowRight size={17}/></button></div></div></article>)}{visible.length===0 && <div className="empty-plan"><Bookmark size={30}/><h3>{tab==='saved'?'Your next adventures belong here.':'No trails match just yet.'}</h3><p>{tab==='saved'?'Tap the heart on any trail to save it.':'Try a different search or a wider distance range.'}</p><button className="text-button" onClick={()=>{setTab('explore');setQuery('');setDifficulty('All levels');setRegion('All Singapore');setMaxDistance(30);}}>Explore all trails →</button></div>}</div><p className="catalog-note">Lengths from NParks guides. Difficulty reflects terrain and distance. Times are planning estimates at a {fitness.toLowerCase()} pace. Photos are illustrative, not trail-specific.</p></>}
      </div><div className="map-panel"><TrailMap trails={visible} selected={selected} onSelect={setSelected} points={tab==='plan'?points:emptyPoints} route={tab==='plan'?result:null} planning={tab==='plan'} onAdd={addPoint} onMove={(index,point)=>{if(validPoint(point)) setPoints(previous=>previous.map((p,i)=>i===index?point:p)); else setToast('Please keep stops within Singapore.');}}/>{activeTrail && <div className="map-detail"><button className="close-detail" aria-label="Close trail details" onClick={()=>setSelected(null)}><X size={18}/></button><div className="eyebrow dark">YOUR NEXT DETOUR</div><h3>{activeTrail.name}</h3><p>{activeTrail.description}</p><p className="detail-note">{activeTrail.note}</p><div><a href={activeTrail.source} target="_blank" rel="noreferrer">NParks guide & access ↗</a><button className="primary" onClick={()=>{setTab('plan');addPoint(activeTrail.point);setSelected(null);}}>Add entrance <Plus size={15}/></button></div></div>}</div></div>
      </section>
      <section className="outdoor-note"><div className="note-icon"><Sun size={27}/></div><div><h3>A good hike starts before the trail.</h3><p>Pack water. Check the weather. Leave only footprints.</p></div><button onClick={()=>setGuide(true)}>Your pre-hike checklist <ArrowRight size={17}/></button></section>
      <footer><a className="brand" href="/"><Mountain size={22}/> trailfolk<span className="brand-sg">SG</span></a><span>Small island. Endless reasons to get outside.</span><a href="https://www.onemap.gov.sg/" target="_blank" rel="noreferrer">Maps by OneMap / SLA ↗</a></footer>
    </main>
    {toast && <div className="toast" role="status"><Check size={17}/>{toast}</div>}
    {guide && <div className="modal-backdrop" onClick={()=>setGuide(false)}><section className="guide-modal" role="dialog" aria-modal="true" aria-label="Hiking essentials" onClick={e=>e.stopPropagation()}><button className="close-detail" autoFocus aria-label="Close hiking essentials" onClick={()=>setGuide(false)}><X/></button><span className="benefit-icon"><Trees/></span><h2>A little preparation.<br/>A better day out.</h2><p>Before you head for the trees, make these part of your routine.</p>{['Bring drinking water, a snack and a charged phone.','Check rain and lightning forecasts before leaving.','Check park opening hours and temporary closures.','Wear shoes with grip and keep to marked public trails.','Tell someone your plan and leave time to return in daylight.'].map(text=><label className="checklist-item" key={text}><input type="checkbox"/>{text}</label>)}<div className="guide-links"><a href="https://www.weather.gov.sg/" target="_blank" rel="noreferrer">Singapore weather ↗</a><a href="https://www.nparks.gov.sg/visit" target="_blank" rel="noreferrer">NParks visitor information ↗</a></div><p className="small-note">This planner does not provide live closure, elevation or emergency navigation data. Save your itinerary and use official trail signs on the ground.</p></section></div>}
  </>;
}
